
title: Groome - HR and Staffing solution
email: your-email@example.com
description: >-
 Groome,the AI-enabled HR Solution to find,hire,manage and retain best talents.Request for a free demo of our Talent CRM and Application Tracking System now!
url: "https://groome.co/"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed 
  - jekyll-sitemap 
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
  
